apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- hr.yaml
- ns.yaml
- repo.yaml 
patches:
  - target:
      kind: HelmRelease
    path: kubectl.servicemonitor.patch.yaml
  - target:
      kind: HelmRelease
    path: thanos-side-car.patch.yaml
  - target:
      kind: HelmRelease
    path: thanos-service.patch.yaml 
  - target:
      kind: HelmRelease
    path: resources.patch.yaml